version: '3.6'
services:
  pgsql:
    image: postgres:10.4-alpine
    container_name: muxrest-pgsql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: muxrest
      POSTGRES_USER: muxrest
      POSTGRES_PASSWORD: muxrest
    networks:
      - muxrest
  pgsql-tests:
    image: postgres:10.4-alpine
    container_name: muxrest-pgsql-tests
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: muxrest_test
      POSTGRES_USER: muxrest_test
      POSTGRES_PASSWORD: muxrest_test
    networks:
      - muxrest

networks:
  muxrest:
    driver: bridge
volumes:
  muxrest-pgsql:
    driver: local